apiVersion: v1
kind: LimitRange
metadata:
  name: demolimitrange
  namespace: demons
spec:
  limits:
  - default:
      memory: 500Mi
    defaultRequest:
      memory: 100Mi
    type: Container