apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    name: demo
    env: dev
spec:
  containers:
  - name: demo-sample
    image: nginx:latest 
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
