apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
   - name: my-pv
     persistentVolumeClaim:
       claimName: mypvc-hostpath
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
       - mountPath: "/app-data"
         name: my-pv
