apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role2
  namespace: demons
subjects:
- kind: Group 
  name: development 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: demo-role2
  apiGroup: rbac.authorization.k8s.io