apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    name: demo
spec:
  containers:
  - name: demo
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: username
        valuefrom:
          secretKeyRef:
            name: mysecret
            key: username
    volumeMounts:
      - name: secret 
        mountPath: /mydata        
  volumes:
  - name: secret 
    configMap:
      name: mysecret